### ISSUE TITLE
[Feature]: please increase memory of storage 

### ISSUE THREAD

**Issue by belikefrustu** [xeffyr/android-vshell#20] opened 2021-09-21 07:53 UTC
### Feature description

We can limited packages install ..so I want to install unlimited package... Because sometimes get no space left error ..even docker need more space for package

### Design limits acknowledgement

- [X] I have read and understand [LIMITATIONS.md](https://github.com/xeffyr/android-vshell/blob/master/LIMITATIONS.md)

**Comment by xeffyr** [comment] 2021-09-21 09:24
By default the rootfs is stored in RAM, i.e. vShell uses a diskless installation of Alpine Linux. Root fs size is 1/2 of RAM allocated for the VM.

If need more, perform on-disk installation as shown in motd displayed after login. You may re-partition hdd to extend default 4GB partition.

https://github.com/xeffyr/android-vshell#properties-of-emulated-vm

Wontfix since this is intended by design.

**Closed by xeffyr** 2021-09-21 09:24 UTC
Labels: enhancement
